### ISSUE TITLE
model gpt-4 doesn't exist even with paid plan

### ISSUE THREAD

**Issue by twist3dimages** [muellerberndt/mini-agi#38]
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

I keep getting this message even though I am paying for the upgraded plan. 

Relevant config
```
MODEL="gpt-4"
SUMMARIZER_MODEL="gpt-3.5-turbo"

MAX_CONTEXT_SIZE=4000
MAX_MEMORY_ITEM_SIZE=2000
SUMMARIZER_CHUNK_SIZE=3000

CLEAR_DB_ON_START=true
DEBUG=true

#pinecone, postgres, chromadb
MEMORY_TYPE="chromadb"
```

**Comment by muellerberndt** [comment]
The upgraded plan doesn't include GPT-4 by default... you need to get on the waitlist.

https://openai.com/waitlist/gpt-4-api

**Comment by jwestonmoss** [comment]
GPT-4 api access is a game changer.  Been waiting on the waitlist since the day it was announced.  Still waiting.  Bummed lol
