### ISSUE TITLE
no current job

### ISSUE THREAD

**Issue by Iamtheoldman** [muellerberndt/mini-agi#43]
what does that mean?
<img width="441" alt="Screenshot 2023-04-24 at 9 49 57 AM" src="https://user-images.githubusercontent.com/98844780/234049528-91fac1d2-1953-48cf-b019-b4783fa81aa7.png">

**Comment by muellerberndt** [comment]
Weird, sounds like a shell-related issue. What operating system is that?

**Comment by Iamtheoldman** [comment]
Mac m1

**Comment by muellerberndt** [comment]
I think I know what the problem is: You are copying a command including a preceding %. Like this:

% **%** python microgpt.py "Do some tests"

This reproduces the "no current job" error on my Mac.

**Comment by Iamtheoldman** [comment]
Your the goat I’ll try it tomorrow! Thanks
