### ISSUE TITLE
Getting stuck in repeating loops

### ISSUE THREAD

**Issue by jwestonmoss** [muellerberndt/mini-agi#47]
This could be a reflection of the fact that 3.5 is a weaker model, but the agent is getting stuck in essentially repeating loops, some examples:

Trying to install the same package over and over across multiple prompts

Trying to create the same file or folder over and over again, succeeding the first time and then failing ever after that (already exists)

Do you think this is a problem with how I am prompting, is this a micro-gpt issue, a 3.5 issue, or a ThinkGPT issue?

**Comment by jwestonmoss** [comment]
Thanks for your help, this is very exciting stuff

**Comment by muellerberndt** [comment]
> Do you think this is a problem with how I am prompting, is this a micro-gpt issue, a 3.5 issue, or a ThinkGPT issue?

It's less of an issue with GPT-4. But we could still try to address it on the ThinkGPT level. One option would be adding a critic that checks the actions of the agent for loops and other misbehavior. That's something we are exploring.

**Comment by muellerberndt** [comment]
Added a critic that should detect loops (although they sometimes still don't get detected when using GPT-3.5-Turbo).
