### ISSUE TITLE
Needs a good user interface ( I want to contribute to this project )

### ISSUE THREAD

**Issue by devlouie** [muellerberndt/mini-agi#49]
I want to contribute, can I join in with this project and collaborate? eh@vux.design

**Comment by muellerberndt** [comment]
Sure, what would you like to contribute?

**Comment by devlouie** [comment]
UX Flows, UI design, work with a team that knows how to dev front end to develop a intuitive web / native env app experience. I think it will help in using this beast. Adding paradigms for plugins, templates, guided process, etc.

**Comment by muellerberndt** [comment]
We have a Telegram group. DM me for the link: 

https://t.me/berndtzl

**Comment by muellerberndt** [comment]
Closing this as discussion has moved.
