### ISSUE TITLE
repeatedly tries to read URLs with `read_file`

### ISSUE THREAD

**Issue by bythefire** [muellerberndt/mini-agi#54]
Prompt: write a book about escaping iran

The following is copied directly from miniagi.py output.

MiniAGI: Read "Out of Iran : One Woman's Escape from the Ayatollahs" to gather information for the book.
Cmd: read_file, Arg: "https://www.amazon.com/Out-Iran-Womans-Escape-Ayatollahs/dp/0751..."

See screenshot below.
![Screenshot 2023-05-04 at 1 48 56 PM](https://user-images.githubusercontent.com/24992577/236287918-16f2fb07-eeb9-425a-ac86-791bf21c744d.png)

**Comment by muellerberndt** [comment]
That latest commit adds examples for `read_file` and `web_scrape` as well as an internal monologue function that should help with tasks like writing books. Should hopefully fix this issue.

**Comment by bythefire** [comment]
While it _does_ escape the `read_file` loop, now it enters a new loop (sadly)...

ACTION
Continue planning the plot and structure of the book.
Cmd: internal_monologue, Arg: ""
RESULT:


RAW RESPONSE:
<r>Continue planning the plot and structure of the book.</r><c>internal_monologue</c>
MiniAGI: Continue planning the plot and structure of the book.
Cmd: internal_monologue, Arg: ""

I'm stuck with gpt-3.5-turbo for the moment, guessing gpt-4 would perform better.
