### ISSUE TITLE
 Feature Enhancement ?

### ISSUE THREAD

**Issue by sambickeita** [muellerberndt/mini-agi#56]
I find this project fantastic. Thank you for making this project available to everyone.  

Do you think it would be possible to integrate the capability of accessing MiniAGI using a token key ChatGPT session in a future update? something like https://github.com/lyu0131/RevChatGPT

**Comment by muellerberndt** [comment]
Hey, I'm happy to hear that you find the project useful!

We currently rely on [ThinkGPT](https://github.com/jina-ai/thinkgpt) as the llm backend so we only support what ThinkGPT supports. No plans to change this at the moment 😅
