### ISSUE TITLE
Critic becomes agent

### ISSUE THREAD

**Issue by Happiness777** [muellerberndt/mini-agi#57]
Hi.
There were situations, where critic became agent, for some reason.
It's trying to speak like agent, and apologizes if something goes wrong.
Basically it does anything but criticism.

**Comment by muellerberndt** [comment]
Do you have some example output?

**Comment by Happiness777** [comment]
> Do you have some example output?

Right now, no, but when it'll happen again, I'll share it.

**Comment by Happiness777** [comment]
It happened again.
The goal was to write a song in Russian, that would rhyme.

(Works fine for now)
![Screenshot_2023-05-19-10-14-38-327_com termux](https://github.com/muellerberndt/mini-agi/assets/35190676/bc327701-190f-4cca-b8aa-f99ccf233161)


(Breaks completely)
![Screenshot_2023-05-19-10-14-42-270_com termux](https://github.com/muellerberndt/mini-agi/assets/35190676/bbf8f5ed-cecc-438a-b7e3-a00cd44054b3)


My guess is that user input is throwing the critic off, and it's trying to reply to user.
I've tried to modify the critic prompt multiple times, but it still was prone to breaking on user input.

**Comment by muellerberndt** [comment]
The latest commit (as of today) no longer calls the critic on user input. I tested with a German poem & didn't experience the bug. Can you confirm?

**Comment by Happiness777** [comment]
> The latest commit (as of today) no longer calls the critic on user input. I tested with a German poem & didn't experience the bug. Can you confirm?

Unfortunately, I can't check it right now.
I ran out of quota :(

**Comment by Happiness777** [comment]
Hello again.
It seems it has been fixed.
I'll update this issue if it happens again.

By the way, have you considered making a discord server?

**Comment by muellerberndt** [comment]
I don’t think the project is popular enough to warrant a Discord server… also I wouldn’t have time to maintain it 😅

**Comment by Happiness777** [comment]
> I don’t think the project is popular enough to warrant a Discord server… also I wouldn’t have time to maintain it 😅

Oh, ok then.
I guess I'll close the issue now, since it seems to be resolved.
