### ISSUE TITLE
match command.  invalid syntax

### ISSUE THREAD

**Issue by sennoy11012** [muellerberndt/mini-agi#59]
he drawing in an image format of your choice."
Traceback (most recent call last):
  File "miniagi.py", line 23, in <module>
    from commands import Commands
  File "**/mini-agi/commands.py", line 32
    match command:
          ^
SyntaxError: invalid syntax

**Comment by Happiness777** [comment]
@sennoy11012 what is the python versions you're using?

Try `python3 -V`.
Don't use just `python`, because it'll most likely will be python 2.7, which is incompatible with the project, I think.

**Comment by muellerberndt** [comment]
Hey @sennoy11012, MiniAGI requires Python 3.10 or higher to work. I will add this requirement to the README.
