### ISSUE TITLE
Error running via docker

### ISSUE THREAD

**Issue by AndrukhivAndriy** [muellerberndt/mini-agi#63]
Change ./run.sh and add "mkdir -p appdata" before "cp .env ./appdata" . It makes copy of env file, but don't copy it to dir

**Comment by muellerberndt** [comment]
Hey @AndrukhivAndriy, thanks for the bug report. Would you like to submit a PR?

**Comment by muellerberndt** [comment]
Nevermind, it's fixed in [d2add8f](https://github.com/muellerberndt/mini-agi/commit/d2add8f18caf96934a2d193583720cfc9b89451b).
